apiVersion: v1
kind: Service

metadata:
  name: orderapi-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: orderapi

  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.orderapi.port }}

  type: ClusterIP