apiVersion: v1
kind: Service

metadata:
  name: productapi-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: productapi

  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.productapi.port }}

  type: ClusterIP