trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azure-service-connection'
  acrName: 'lokeshacr2026'
  acrLoginServer: 'lokeshacr2026.azurecr.io'
  resourceGroup: 'rg-learning-dev'

  productImage: 'productapi'
  orderImage: 'orderapi'

  productContainerApp: 'productapi-container'
  orderContainerApp: 'orderapi-container'

  imageTag: '$(Build.BuildId)'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Build Push and Deploy Docker Images'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(acrName)

      docker build -t $(acrLoginServer)/$(productImage):$(imageTag) ProductApi
      docker push $(acrLoginServer)/$(productImage):$(imageTag)

      docker build -t $(acrLoginServer)/$(orderImage):$(imageTag) OrderApi
      docker push $(acrLoginServer)/$(orderImage):$(imageTag)

      az containerapp update \
        --name $(productContainerApp) \
        --resource-group $(resourceGroup) \
        --image $(acrLoginServer)/$(productImage):$(imageTag)

      az containerapp update \
        --name $(orderContainerApp) \
        --resource-group $(resourceGroup) \
        --image $(acrLoginServer)/$(orderImage):$(imageTag)