trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'azure-service-connection'
  acrName: 'lokeshacr2026'
  acrLoginServer: 'lokeshacr2026.azurecr.io'
  resourceGroup: 'rg-learning-dev'
  aksCluster: 'ecommerce-aks'
  namespace: 'ecommerce'
  imageTag: '$(Build.BuildId)'
  helmRelease: 'ecommerce'
  helmChartPath: './helm/ecommerce'

stages:
- stage: CI
  displayName: Build and Push Images
  jobs:
  - job: BuildPush
    steps:
    - task: AzureCLI@2
      displayName: Build and Push Docker Images
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

          docker build -t $(acrLoginServer)/productapi:$(imageTag) ./ProductApi
          docker push $(acrLoginServer)/productapi:$(imageTag)

          docker build -t $(acrLoginServer)/orderapi:$(imageTag) ./OrderApi
          docker push $(acrLoginServer)/orderapi:$(imageTag)

          docker build \
            --build-arg VITE_ORDER_API_BASE_URL=http://135.235.150.67/api/orders \
            -t $(acrLoginServer)/ecommerce-ui:$(imageTag) ./ecommerce-ui

          docker push $(acrLoginServer)/ecommerce-ui:$(imageTag)

- stage: CD
  displayName: Deploy to AKS using Helm
  dependsOn: CI
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      displayName: Helm Upgrade to AKS
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials \
            --resource-group $(resourceGroup) \
            --name $(aksCluster) \
            --overwrite-existing

          helm upgrade --install $(helmRelease) $(helmChartPath) \
            --namespace $(namespace) \
            --create-namespace \
            --set productapi.tag=$(imageTag) \
            --set orderapi.tag=$(imageTag) \
            --set ui.tag=$(imageTag)

          kubectl rollout status deployment/productapi-deployment -n $(namespace)
          kubectl rollout status deployment/orderapi-deployment -n $(namespace)
          kubectl rollout status deployment/ecommerce-ui-deployment -n $(namespace)

          kubectl get pods -n $(namespace)
          kubectl get svc -n $(namespace)
          kubectl get ingress -n $(namespace)