apiVersion: v1
kind: Secret

metadata:
  name: orderapi-secrets
  namespace: ecommerce

type: Opaque

stringData:
  ServiceBus__ConnectionString: "Endpoint=sb://xxxxxxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxx"